#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:-.env}"

warn_if_exists() {
  local key="$1"
  if [ -f "$ENV_FILE" ] && grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
    echo "WARNING: $key already exists in $ENV_FILE — skipping" >&2
    return 1
  fi
  return 0
}

echo "# Generated by generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"

for key in MASTER_KEY SERVER_PEPPER; do
  if warn_if_exists "$key"; then
    echo "${key}=$(openssl rand -base64 32)"
  fi
done

if warn_if_exists "MANIFEST_SIGNING_KEY"; then
  echo "MANIFEST_SIGNING_KEY=$(openssl rand -base64 64 | tr -d '\n')"
fi

if warn_if_exists "ADMIN_API_SECRET"; then
  echo "ADMIN_API_SECRET=$(openssl rand -hex 32)"
fi
